version: "3"
# SPDX-FileCopyrightText: © 2022 Kaspa Developers
# SPDX-License-Identifier: ISC

services:
  kaspad:
    container_name: kaspad
    image: hlxeasy/docker-kaspad:latest
    restart: unless-stopped
    expose:
      - "16110/tcp"
      - "16111/tcp"
    volumes:
      - kaspad1:/root/.kaspad/
    command: kaspad --utxoindex --enablebanning --whitelist=192.168.0.0/16

  kaspawallet:
    container_name: kaspawallet
    image: hlxeasy/docker-kaspad:latest
    restart: unless-stopped
    volumes:
      - kaspawallet:/root/.kaspawallet/
    command:
      - /bin/bash
      - -c
      - |
        while true ; do
          if [ -e /root/.kaspawallet/kaspa-mainnet/keys.json ] ; then
            kaspawallet start-daemon --rpcserver kaspad
          else
            echo "/root/.kaspawallet/kaspa-mainnet/keys.json not found, checking again in 60s"
            sleep 60
          fi
        done
volumes:
  kaspad1:
  kaspawallet:
